spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gateway
    username: postgres
    password: mysecretpassword
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    gateway:
      routes:
        - id: simService1
          uri: http://localhost:8081
          predicates:
              - Path=/sim1/**
        - id: simService2
          uri: http://localhost:8082
          predicates:
            - Path=/sim2/**
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.web.reactive.function.server: DEBUG
aes:
  key:
    default: XouC4mCuRewmUY1ZP4FBPZPEZdMXmdllJzAXDIP9a+4=