server:
  port: 8181
spring:
  application:
    name: simClient
  datasource:
    url: jdbc:postgresql://localhost:5432/gateway
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
aes:
  key:
    default: XouC4mCuRewmUY1ZP4FBPZPEZdMXmdllJzAXDIP9a+4=